name: .NET CI

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - 'exporters/**'
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - 'exporters/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./exporters

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore StrategyExporter.Tests/StrategyExporter.Tests.csproj

    - name: Build
      run: dotnet build StrategyExporter.Tests/StrategyExporter.Tests.csproj --no-restore

    - name: Test
      run: dotnet test StrategyExporter.Tests/StrategyExporter.Tests.csproj --no-build --verbosity normal
